# Generated by Django 2.0.2 on 2018-04-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'カクテル',
                'verbose_name_plural': 'カクテル一覧',
            },
        ),
        migrations.CreateModel(
            name='HowToMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '製法',
                'verbose_name_plural': '製法一覧',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '種別',
                'verbose_name_plural': '種別一覧',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_show', models.BooleanField(default=True)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Kind')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料一覧',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Cocktail')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Material')),
            ],
            options={
                'verbose_name': 'レシピ',
                'verbose_name_plural': 'レシピ一覧',
            },
        ),
    ]
