# Generated by Django 2.0.2 on 2018-04-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='how_to_make',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.HowToMake'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='materials',
            field=models.ManyToManyField(through='learn_cocktail.Recipe', to='learn_cocktail.Material'),
        ),
    ]
