# Generated by Django 2.0.2 on 2018-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_cocktail', '0005_auto_20180430_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='materials',
            field=models.ManyToManyField(related_name='recipe_materials', through='learn_cocktail.Recipe', to='learn_cocktail.Material'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='howtomake',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
