# Generated by Django 2.0.2 on 2018-05-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_cocktail', '0006_auto_20180507_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='how_to_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.HowToMake', verbose_name='製法'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='表示可否'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='materials',
            field=models.ManyToManyField(related_name='recipe_materials', through='learn_cocktail.Recipe', to='learn_cocktail.Material', verbose_name='原料名'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='カクテル名'),
        ),
        migrations.AlterField(
            model_name='howtomake',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='表示可否'),
        ),
        migrations.AlterField(
            model_name='howtomake',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='製法名'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='表示可否'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='種別名'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='表示可否'),
        ),
        migrations.AlterField(
            model_name='material',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Kind', verbose_name='カクテル種別'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='原料名'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Cocktail', verbose_name='カクテル'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_cocktail.Material', verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='分量'),
        ),
    ]
