# Generated by Django 2.0.5 on 2018-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_cocktail', '0009_auto_20180507_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='importance',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='頻出度合い'),
        ),
    ]
