# Generated by Django 2.0.5 on 2018-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_cocktail', '0010_cocktail_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='alc_percent',
        ),
        migrations.AddField(
            model_name='material',
            name='alc_percent',
            field=models.FloatField(default=0.0, verbose_name='度数(%)'),
        ),
    ]
